import type { Metadata } from "next";
import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
  title: "MovieBox",
  description: "Generated by create next app",
};

export default function DescriptionLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full h-full min-h-[100vh] flex justify-center items-center">
      <SideBar />
      {children}
    </div>
  );
}
